### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bubnov-mikhail** [badrsk1x/Tracker#1]
1 - Use short array syntax array() -> []
2 - Use EntityClass::class constant instead of a string in EntityManager::getRepository()
3 - In Tracker/src/UserBundle/EventListener/LogoutListener and LoginListener you are creating a new Tracker entity with action set to 'logout' and 'login'. What will happen if a user will login from one machine and without logging out will login on another?
5 - What is the AppBundle for? And the AppBundle\DefaultController::indexAction has the same route as the UserBundle\DefaultController::indexAction
6- Do not query mysql in a controller. You should use a repository for this. Also use setParameter() and not this: 'SELECT ... FROM ... WHERE user.id=' . $user->getId()
7- Use Project::ACTIVE_PROJECT instead of $project::ACTIVE_PROJECT
8- Why are you not using the Form component provided by Symfony but renders it manually in a template?
9- You may move all 'app.session.flashBag' from each template to the base.html.twig
10- In the TrackerController::newAction() you are moving an uploaded file to a new location and using a username as a part of the file. What if my user name is like "my/../user/"?
11- Same method, line 55 (fopen(__DIR__ . "/../../../web/uploads/".$filename, "r")) - use parameter with a path to upload direcotry.
12- There is a nice bundle "vich/uploader-bundle" for handling user uploaded files. Feel free to use it.
13- Fat controllers is not the best practice. Move you business logic to a service or at least extract it to methods. Controllers are only for handling requests and answering responses.
14- Same method, line 65. What will happen if there is no element under index 1? The csv file may have a line with only one ","
15- Same method, line 62. You are doing the same in the loop body. Not using vars $c or $num
16- Same method, line 83. I did not get it. What are you trying to do here? You already have a user, why are you fetching it again? Just call $user->getProject();
17- Do not call EntityManager::flush() in a loop. DO it once after a loop!
18- ProjectBundle\ProjectController, "if(...): ... endif;" Better to change to "if () {}" Or at least use the same syntax everywhere.
19- Same line, use strict compare "$something === null"
-20 Same class, line 92. Calling $userManager->findUserBy(...) will trigger a DB. What if there are hundred millions of records in this loop?
21- Same method. You are going to render all records in a template. What if there are hundred millions of records. My suggestion is to use a pagination for displaying.
22- ProjectController::peaktimeAction() has no @Route annotation. How will you reference to this method in you form?
23- There is an input[name="date" type="text"] in your form. Do you have any anti SQL injection check before pushing it's value to an SQL? Same for the project input.

**Comment by badrsk1x** [comment]
1=> Done
2=> Done ( it was already , but actually not everywhere *)
5=>Deleted ( * )
6=>Done ( absolutely true, i Agree, thanks)
7=>Done ( it was already , but actually not everywhere *)
8=>Actually i did, add_csv.html.twig ( maybe you mean in the form in peaktimehome.html.twig *)
9-12 - I changed to vichupload, actually i nkow thi sbundle before, but as it was a test task, i thaught that possible to work without it 
14-16=>Done
17-20=>Done
23=> Because of the nature of the ORM database style in Symfony2 we are naturally protected from SQL injection. Data that does not match the constraints set by the configuration or Validator class will be rejected before reaching the database anyways.

* = It was at task to do shortly, within couple of days, that s why so moments was done in a hurry
